[package]
edition = "2018"
name = "status"
version = "0.0.0"

[dependencies]
chrono = "0.4"
inotify = "0.9"
libpulse-binding = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swaybar-types = "2"
tokio = { version = "1", features = ["full"] }
